version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "CHECK"
leavesCullingAmount = 2
includeMangroveRoots = true
endGatewayCulling = true
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
farmersdelight = true
storagedelight = true
toughasnails = false
eldritch_mobs = true
easymagic = true
brewinandchewin = true
easyanvils = true
another_furniture = true
friendsandfoes = true
runes = true
natures_spirit = true
earlystage = true
comforts = true
hauntedharvest = true
ends_delight = true
fishermens_trap = true
village_taverns = true
yigd = true
amendments = true
mynethersdelight = true
dehydration = true
snowrealmagic = false
vegandelight = true
treechop = true
exposure = true
spell_engine = true
corndelight = true
cratedelight = true
grassoverhaul = true
ubesdelight = true
paladins = true
sawmill = true
endrem = true
frightsdelight = true
sereneseasons = true
visualworkbench = false
rogues = true
minecraft = true
philipsruins = true
natures_delight = true
rusticdelight = true
betterarcheology = true
dumplings_delight = true
fleshz = true
jewelry = true
bosses_of_mass_destruction = true
waystones = true
creeperoverhaul = true
archers = true
